### ISSUE TITLE
How to initialize properly in es5?

### ISSUE THREAD

**Issue by dylanfpaul** [phazelift/react-scroll-listener#1]
In your readme example, in your componentDidMount example:

```
componentDidMount: function(){
    scrollListener.addScrollHandler('some-id', myScrollStartHandler, myScrollEndHandler );
}
```

Where did you declare 'scrollListener'? I don't see it being declared anywhere else in your example.

**Comment by dylanfpaul** [comment]
Sorry I mean es6, not es5.

**Comment by phazelift** [comment]
Hi,

You're right it is a typo, thx for pointing me to that one. The creation of
the instance should be starting with a lowercase of course.. I've updated
the readme.

Personally I only use the Mixin as I consider it more convenient, but
something like this should work in ES6:

import ScrollListener from 'react-scroll-listener';

const scrollListener = new ScrollListener();

const myScrollStartHandler = function(){
console.log( 'logs on every scroll move' );
};

const myScrollEndHandler = function(){
console.log( 'logs only when scrolling has stopped (default 300ms delay)' );
};

const myComponent= React.createClass({

componentDidMount: function(){
scrollListener.addScrollHandler('some-id', myScrollStartHandler,
myScrollEndHandler );
},

render: function(){
return (

<div>Some content</div>

);
}

});

Best,
Dennis

**Comment by dylanfpaul** [comment]
Right on, thanks. Also, this may be obvious to most but I was wondering if the intended functionality of this component is just a scroll listener? For instance, does this component just fire handlers on _every_ scroll, or are there ways to make it fire when the user has scrolled all the way to the bottom of the page for instance?

**Comment by phazelift** [comment]
Basically it fires handlers, although not 'just', it attempts to do it more
efficiently. And as a mixin it takes care of setting and removing the
handlers on mount and unmount. I prefer to keep my npm modules really
basic, so if you want to test scroll bounds you could try something like
this in a react component with the mixin injected:

onScrollEnd: function(){
var divHeight= document.getElementById( 'some-div-id' ).scrollHeight;

if ( this.scrollListener.scrollTop >= divHeight ){
// do something
}
}

You could also do this onScrollStart, but that's more expensive, especially
something to be aware of when developing for mobile devices.
