### ISSUE TITLE
Providing the ScrollEvent object to the handlers

### ISSUE THREAD

**Issue by willmorgan** [phazelift/react-scroll-listener#2]
Is there a reason why the ScrollEvent object isn't passed through to the scroll handlers? It would be handy to use so that scroll locking can be implemented, and so on.

**Comment by phazelift** [comment]
Hi,

Thanks Will, very valid point. The short reason is that I didn't need that
when I wrote it. I'll add it somewhere this week if I can find some time.

**Comment by phazelift** [comment]
It's done. The event is passed to onScrollStart and onScrollEnd.

**Comment by willmorgan** [comment]
Cheers @phazelift, much appreciated! ❤️
