### ISSUE TITLE
How to detect direction?

### ISSUE THREAD

**Issue by aZolo77** [phazelift/react-scroll-listener#3]
Hi!
This is more like a question:
Can I somehow detect direction (top/bottom)?

Here is my code:

```
import React, { useEffect } from "react";
import ScrollListener from "react-scroll-listener";

const MyComponent = () => {
  const scrollStartHandler = (event) => {
    console.log("logs on every scroll move");
  };

  const scrollEndHandler = (event) => {
    console.log("logs only when scrolling has stopped (default 300ms delay)");
  };

  useEffect(() => {
    const scrollListener = new ScrollListener();
    scrollListener.addScrollHandler(
      "some-id",
      scrollStartHandler,
      scrollEndHandler
    );
  }, []);

  return (
    <div className="mobile-bottom-panel_wrapper">
      <div className="mobile-bottom-panel_content">
        <span>bottom panel</span>
      </div>
    </div>
  );
};

export default MyComponent;
```

**Comment by phazelift** [comment]
Hi @aZolo77,

There is no scroll direction flag in the lib/code, although it could easily be added. I remember that I added as least as possible of these kind of features to keep the handler as lean as possible to not soak host resources. Still, you can easily measure the direction yourself by calculating the difference between the begin and end position of the .scrollTop between a scroll start and a scroll end event. If you need it realtime then you would probably need to use the original scroll event that is also passed to the scroll start handler as argument. But take into account that the latter can be quite costly on resources. Hope this helps.

**Comment by aZolo77** [comment]
Thanks!
